POST https://simpsons-classification.westeurope.inference.ml.azure.com/score HTTP/1.1
content-type: application/json
Authorization: Bearer dQkoYY7Iw8j1Nobro1IZRQkRQRkReXmo

{
    "image": "https://raw.githubusercontent.com/hnky/dataset-lego-figures/master/_test/Bart.jpg"
}
 