POST https://simpsons-demo.westeurope.inference.ml.azure.com/score HTTP/1.1
content-type: application/json
Authorization: Bearer iVXO2U5j2Lga3mo8UE1unPd29NFYw7uP

{
    "image": "https://raw.githubusercontent.com/hnky/dataset-lego-figures/master/_test/Homer.jpg"
}
 