$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: Simpsons-Demo
code:
  local_path: ../scripts/train
command: python train.py --data ${{inputs.training_data}} --num-epochs ${{inputs.epochs}} --learning_rate ${{inputs.learning_rate}} --momentum ${{inputs.momentum}}
environment: azureml:AzureML-pytorch-1.10-ubuntu18.04-py38-cuda11-gpu:2
compute: azureml:OptimusPrime
inputs:
  epochs: 10
  learning_rate: 0.001
  momentum: 0.9
  training_data:
    dataset: azureml:LegoSimpsons-v3:3