$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: pytorch1
endpoint_name: simpsons-classification
model: azureml:simpsons-classification-pytorch:3
code_configuration:
  code: 
    local_path: ./pytorch
  scoring_script: score.py
environment:
  conda_file: ./pytorch/conda.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210727.v1
instance_type: Standard_F2s_v2
instance_count: 1